services:
  postgres:
    container_name: raffley_postgres
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raffley_dev
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
